# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='index',
        ),
    ]
