# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 13:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('text', '0002_auto_20170927_1334'),
        ('rules', '0002_auto_20170926_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inconsistency',
            name='inconsistencyType_id_fk',
        ),
        migrations.RemoveField(
            model_name='inconsistency',
            name='rule_id_fk',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='rule_type_fk',
        ),
        migrations.AddField(
            model_name='inconsistency',
            name='fragment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='text.Fragment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inconsistency',
            name='inconsistency_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='rules.InconsistencyType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inconsistency',
            name='rule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='rules.Rule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inconsistency',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rule',
            name='rule_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='rules.RuleType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rule',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
