# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_auto_20170927_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='user',
        ),
    ]
