# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 23:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rules', '0004_remove_rule_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
