# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_rule_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='weight',
        ),
        migrations.AlterField(
            model_name='rule',
            name='warning',
            field=models.TextField(max_length=100),
        ),
    ]
