# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0006_auto_20171004_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inconsistency',
            options={'verbose_name': 'Inconsistency', 'verbose_name_plural': 'Inconsistencies'},
        ),
    ]
