# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0007_auto_20171005_1225'),
        ('rules', '0007_auto_20171005_1028'),
    ]

    operations = [
    ]
